### ISSUE TITLE
"no exchange 'dashboard@92b9d5115d49' in vhost '/'"

### ISSUE THREAD

**Issue by dconathan** [nextml/NEXT#119]
With latest redux update (we believe this has something to do with [this commit](https://github.com/nextml/NEXT/commit/a198414e53c86d482f3ec7b6d66cb9c0ed09fae1), I can launch an experiment and go to the dashboard, but when I try to open a query it gets stuck on loading and says "Waiting for available socket"

Here is the only error I see from the backend:
```
[35mrabbitmq_1          | [0m=ERROR REPORT==== 7-Jun-2016::22:10:43 ===
[35mrabbitmq_1          | [0mChannel error on connection <0.1476.0> (xxx.xx.x.x:xxxxx -> xxx.xx.x.x:xxxx, vhost: '/', user: 'guest'), channel 1:
[35mrabbitmq_1          | [0moperation basic.publish caused a channel exception not_found: "no exchange 'dashboard@92b9d5115d49' in vhost '/'"
```
(where xxx.etc. are ip addresses/ports).

**Comment by kgjamieson** [comment]
I may have corrected this by correcting a typo in next_worker_startup.sh -
I just pushed. Let me know if not

**Comment by dconathan** [comment]
Now backend doesn't start (it locks up mid launch), maybe because of this?

```
[34mrabbitmqmonitor_1   | [0mpython: can't open file './next/broker/cluster_monitor.py': [Errno 2] No such file or directory
[34mcode_rabbitmqmonitor_1 exited with code 2
```

Don't know if this is related but I'm also now getting this error again:
```
[36;1mminionworker_1      | [0mValueError: 'CELERYD_PREFETCH_MULTIPLIER': invalid literal for int() with base 10: ''
```

(the fix from [issue 107](https://github.com/nextml/NEXT/issues/107) where I set that variable in my docker-compose is still there...)

**Comment by dconathan** [comment]
Copied the `cluster_monitor.py` from an older version of next just to see what would happen.  Unsurprisingly, it complains that it is missing some methods... though the system no longer locks up.  Still seeing the `'CELERYD_PREFETCH_MULTIPLIER'` error

**Comment by dconathan** [comment]
@lalitkumarj thinks my docker-compose needs to be updated... probably the case... he is working on that...

**Comment by kgjamieson** [comment]
Yes - The rabbit monitor was ripped out of docker compose (and Next)

**Comment by dconathan** [comment]
Fixed, indeed had to update my docker-compose to reflect new changes.
